baseURL = "https://sunri.ink/"
languageCode = "zh-cn"
# theme = "anubis2"
theme = "hugo-theme-ladder"
title = "SunR1's Internet Garden"

colorTheme = "auto"
colorThemeSwitcher = true

[author]
name = "SunR1"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

# [menu]
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Learn"
pageRef = "/learn"
weight = 3