baseURL = 'https//sunri.ink/'
languageCode = "zh-cn"
theme = "anubis2"
title = "SunR1's Internet Garden"

colorTheme = "light"
colorThemeSwitcher = true

[author]
name = "SunR1"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[menu]
[[menu.main]]
name = "Home"
pageRef = '/'
weight = 1

[[menu.main]]
name = "Blog"
pageRef = '/blog'
weight = 2

[[menu.main]]
name = "About"
pageRef = '/about'
