baseURL = "https://sunri.ink/"
languageCode = "en-us"
theme = "anubis2"
title = "SunR1's Internet Garden"

colorTheme = "light"
colorThemeSwitcher = true

[author]
name = "SunR1"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "https://sunri.ink/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://sunri.ink/blog"
weight = 2

