baseURL = "sunri.ink"
languageCode = "en-us"
theme = "anubis2"
title = "SunR1's Internet Garden"

colorTheme = "dark"
colorThemeSwitcher = true

[author]
name = "SunR1"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 2

