baseURL = "https://sunri.ink/"
title = "SunR1's Internet Garden"
theme = "hugo-theme-ladder"
license = "MIT"
homepage = "https://sunri.ink/blog"
defaultContentLanguage = "en"
# googleAnalytics = "G-7E4JNTL3ES"
# enableRobotsTXT = true
paginate = 8
hasCJKLanguage = true
# copyright = "2023 GuangzhengLi All rights reserved"

[Author]
name = "SunR1"

[params]
brand = "HOME"
# avatarURL = "/images/avatar.png"
author = "SunR1"
# authorDescription = "A clean, fast hugo theme focused on Reading"
# info = "Build a free and beautiful blog site to record your thoughts and increase your influence"
# favicon = "/images/avatar.ico"
darkModeTheme = "data-dark-mode"

  [params.options]
  showDarkMode = true
  enableImgZooming = true
  enableMultiLang = false
  showMetaTags = false

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[[languages.en.menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[languages.en.menu.main]]
name = "Learn"
url = "/learn"
weight = 3

[[languages.en.menu.main]]
name = "Archive"
url = "/archives"
weight = 4



